import { Injectable } from '@angular/core';
import {Position, Seat} from '../classes/seat';
import {elementEventFullName} from '@angular/compiler/src/view_compiler/view_compiler';

@Injectable({
  providedIn: 'root'
})
export class LayoutService {

  layout: any = [];
  constructor() {
    let rawSeats:any[] = JSON.parse(localStorage.getItem('layout'));

    if (rawSeats) {
      let random_boolean = Math.random() >= 0.5;
      rawSeats.forEach(seat => this.layout.push(new Seat(seat.id,
        new Position(seat.position.x, seat.position.y),
        seat.employeeId,
        seat.matching,
        seat.employeeName)));
    }
    else {
      this.layout = [
        {
          "id":1,
          "position":{
            "x":100,
            "y":350
          },
          "matching":22,
          "class":"match_Level_20"
        },
        {
          "id":2,
          "position":{
            "x":45,
            "y":350
          },
          "matching":22,
          "class":"match_Level_20"
        },
        {
          "id":3,
          "position":{
            "x":200,
            "y":260
          },
          "matching":95,
          "class":"match_Level_90"
        },
        {
          "id":4,
          "position":{
            "x":255,
            "y":260
          },
          "matching":95,
          "class":"match_Level_90"
        },
        {
          "id":5,
          "position":{
            "x":100,
            "y":260
          },
          "matching":45,
          "class":"match_Level_40"
        },
        {
          "id":6,
          "position":{
            "x":45,
            "y":260
          },
          "matching":45,
          "class":"match_Level_40"
        },
        {
          "id":7,
          "position":{
            "x":200,
            "y":205
          },
          "matching":95,
          "class":"match_Level_90"
        },
        {
          "id":8,
          "position":{
            "x":255,
            "y":205
          },
          "class":"unavailable"
        },
        {
          "id":9,
          "position":{
            "x":100,
            "y":205
          },
          "matching":45,
          "class":"match_Level_40"
        },
        {
          "id":10,
          "position":{
            "x":45,
            "y":205
          },
          "matching":45,
          "class":"match_Level_40"
        },
        {
          "id":11,
          "position":{
            "x":45,
            "y":405
          },
          "matching":22,
          "class":"match_Level_20"
        },
        {
          "id":12,
          "position":{
            "x":255,
            "y":405
          },
          "matching":12,
          "class":"match_Level_0"
        },
        {
          "id":13,
          "position":{
            "x":200,
            "y":405
          },
          "matching":12,
          "class":"match_Level_0"
        },
        {
          "id":14,
          "position":{
            "x":255,
            "y":350
          },
          "matching":22,
          "class":"match_Level_20"
        },
        {
          "id":15,
          "position":{
            "x":200,
            "y":350
          },
          "matching":22,
          "class":"match_Level_20"
        },
        {
          "id":16,
          "position":{
            "x":100,
            "y":405
          },
          "matching":22,
          "class":"match_Level_20"
        },
        {
          "id":17,
          "position":{
            "x":355,
            "y":350
          },
          "matching":22,
          "class":"match_Level_20"
        },
        {
          "id":18,
          "position":{
            "x":410,
            "y":260
          },
          "matching":65,
          "class":"match_Level_60"
        },
        {
          "id":19,
          "position":{
            "x":355,
            "y":260
          },
          "matching":85,
          "class":"match_Level_80"
        },
        {
          "id":20,
          "position":{
            "x":410,
            "y":205
          },
          "matching":65,
          "class":"match_Level_60"
        },
        {
          "id":21,
          "position":{
            "x":355,
            "y":205
          },
          "matching":85,
          "class":"match_Level_80"
        },
        {
          "id":22,
          "position":{
            "x":410,
            "y":405
          },
          "matching":22,
          "class":"match_Level_20"
        },
        {
          "id":23,
          "position":{
            "x":355,
            "y":405
          },
          "matching":22,
          "class":"match_Level_20"
        },
        {
          "id":24,
          "position":{
            "x":410,
            "y":350
          },
          "matching":22,
          "class":"match_Level_20"
        },
        {
          "id":25,
          "position":{
            "x":314,
            "y":90
          },
          "class":"unavailable"
        },
        {
          "id":26,
          "position":{
            "x":158,
            "y":90
          },
          "class":"unavailable"
        },
        {
          "id":27,
          "position":{
            "x":265,
            "y":520
          },
          "class":"unavailable"
        },
        {
          "id":28,
          "position":{
            "x":210,
            "y":520
          },
          "class":"unavailable"
        },
        {
          "id":29,
          "position":{
            "x":155,
            "y":520
          },
          "class":"unavailable"
        },
        {
          "id":30,
          "position":{
            "x":45,
            "y":520
          },
          "class":"unavailable"
        },
        {
          "id":31,
          "position":{
            "x":100,
            "y":520
          },
          "class":"unavailable"
        },
        {
          "id":32,
          "position":{
            "x":430,
            "y":520
          },
          "class":"unavailable"
        },
        {
          "id":33,
          "position":{
            "x":375,
            "y":520
          },
          "class":"unavailable"
        },
        {
          "id":34,
          "position":{
            "x":320,
            "y":520
          },
          "class":"unavailable"
        }
      ];
  }}

  save(layout:Seat[]){
    localStorage.setItem('layout', JSON.stringify(layout));
  }

  load():Seat[]{
    this.getMatchCase();
    return this.layout;
  }

  getMatchCase(){
    if( this.layout.find(i => i.matching !== undefined)) return;
    let amount = Math.floor(this.layout.length*0.70);
    for(let i=0; i<amount; i++){
      this.layout[i].matching = this.getRandomMatch();
    }
    this.save(this.layout)
  }

  getRandomMatch(): number{
    return Math.floor(Math.random() * 100) + 1;
  }

}
